### ISSUE TITLE
Bragg: ShadowLib calculation does not accept all the materials in ComboBox

### ISSUE THREAD

**Issue by lucarebuffi** [oasys-kit/ShadowOui#127]
ex: Graphite (see ShadowOui-Tutorial example crystal_mosaic

**Comment by srio** [comment]
I will look to this asap

**Comment by srio** [comment]
I see the problem. The python bragg preprocessor only accept cubic fcc [ZincBlende] crystals (is OK for Si, Ge, Diamond, GaAs, etc). It has to be adapted to other structures, like the hexagonal Graphite. The thing is SHADOW cannot accept "any" structure ()like XOPPY) so it in my TODO list since ages to adapt SHADOW to any structure. In the meantime "bragg" should be adapted to Hexagonal Graphite. I pass this issue to  https://github.com/srio/shadow3/issues/21
so it is true that not all the crystal structures in ShadowOui Bragg work.

**Comment by srio** [comment]
The list of crystals is changed to show only those accepted by the preprocessor. Only ZincBlende crystals are accepted plus Graphite that is treated separately.

Shadow3  accepts some other crystals (cubic up to two atomic types) but these are not yet implemented in the python preprocessor.

**Comment by LiMiao-GE-ISS** [comment]
Dear Srio,  if the python BRAGG Preprocessor can only calculate [ZincBlende] crystals so far, how can I simulate the bragg diffraction of other crystals, like AlphaQuartz for example? Although I see the input option of "user defined" by using the "Xop format" data, there is no example data in detail.
